services:
  db:
    image: postgres:16
    container_name: monitor-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "MonitorAtraso2026Forte!"
      POSTGRES_DB: monitor_atraso
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor-api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:MonitorAtraso2026Forte!@db:5432/monitor_atraso"
    env_file:
      - .env

volumes:
  pgdata:
